FROM ruby:3.2.11

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
      build-essential \
      curl \
      default-libmysqlclient-dev \
      default-mysql-client \
      git \
      nodejs \
      npm && \
    npm install -g yarn && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /rails

COPY Gemfile ./

RUN gem install bundler

CMD ["bash"]
